import './globals.css';
import { cn } from '@/src/utils/style';
import { Roboto, Noto_Sans_KR } from 'next/font/google';
import Header from '@/src/components/Header';

const notoSansKr = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['100', '400', '700', '900'],
  variable: '--font-ns',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
  variable: '--font-rb',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={cn(
          notoSansKr.variable,
          roboto.variable,
          'dark:bg-dark flex h-screen w-screen flex-col bg-light font-ns',
        )}
      >
        <Header />
        <main className="flex flex-1 flex-col overflow-y-auto">{children}</main>
      </body>
    </html>
  );
}
